# Generated by Django 4.2 on 2023-04-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_academy_image_alter_ownerprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='choices_images/')),
            ],
        ),
        migrations.CreateModel(
            name='DQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=100)),
                ('direction', models.CharField(choices=[('rtl', 'rtl'), ('ltr', 'ltr')], max_length=100)),
                ('true', models.IntegerField()),
                ('box', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=100)),
                ('direction', models.CharField(choices=[('rtl', 'rtl'), ('ltr', 'ltr')], max_length=100)),
                ('true', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('negative', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(related_name='exam_courses', to='accounts.courses')),
                ('tqs', models.ManyToManyField(related_name='Exam_TQuestion', to='exam.tquestion')),
            ],
        ),
    ]
