# Generated by Django 4.2 on 2023-04-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='dqs',
            field=models.ManyToManyField(related_name='Exam_DQuestion', to='exam.dquestion'),
        ),
    ]
