# Generated by Django 4.2 on 2023-04-22 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_dqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dquestion',
            name='box',
        ),
        migrations.RemoveField(
            model_name='dquestion',
            name='true',
        ),
    ]
