# Generated by Django 4.2 on 2023-04-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_academy_image_alter_ownerprofile_image'),
        ('exam', '0003_remove_dquestion_box_remove_dquestion_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='academy',
            field=models.ManyToManyField(related_name='Exam_Academy', to='accounts.academy'),
        ),
    ]
