# Generated by Django 4.2 on 2023-04-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_academy_image_alter_ownerprofile_image'),
        ('exam', '0007_exam_academy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='academy',
        ),
        migrations.AddField(
            model_name='exam',
            name='academy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.academy'),
        ),
    ]
