# Generated by Django 4.2 on 2023-04-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_exam_academy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='negative',
        ),
    ]
