# Generated by Django 4.2 on 2023-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_remove_exam_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='negative',
            field=models.BooleanField(default=False),
        ),
    ]
