# Generated by Django 4.2 on 2023-04-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_exam_negative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start',
        ),
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
