# Generated by Django 4.2 on 2023-04-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_dquestion_create_tquestion_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dquestion',
            name='level',
            field=models.CharField(choices=[('آسان', 'آسان'), ('متوسط', 'متوسط'), ('سخت', 'سخت')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='level',
            field=models.CharField(choices=[('آسان', 'آسان'), ('متوسط', 'متوسط'), ('سخت', 'سخت')], max_length=100),
        ),
    ]
