# Generated by Django 4.2 on 2023-04-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_remove_dquestion_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tquestion',
            name='true',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
