# Generated by Django 4.2 on 2023-04-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_alter_tquestion_true'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
