# Generated by Django 4.2 on 2023-04-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_alter_choices_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
