# Generated by Django 4.2 on 2023-04-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_academy_image_alter_ownerprofile_image'),
        ('exam', '0021_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='academy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.academy'),
        ),
    ]
