# Generated by Django 4.2 on 2023-04-28 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0024_remove_choices_exam_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teachers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
