# Generated by Django 4.2 on 2023-04-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_exam_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='teachers',
        ),
    ]
