# Generated by Django 4.2 on 2023-04-29 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0026_remove_exam_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='access_teachers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
