# Generated by Django 4.2 on 2023-04-30 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0027_exam_access_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='access_students',
            field=models.ManyToManyField(related_name='exam_s_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='access_teachers',
            field=models.ManyToManyField(related_name='exam_t_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
