# Generated by Django 4.2 on 2023-04-30 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0028_exam_access_students_alter_exam_access_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true', models.PositiveIntegerField()),
                ('question', models.ManyToManyField(to='exam.tquestion')),
                ('student', models.ManyToManyField(related_name='answer_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
