# Generated by Django 4.2 on 2023-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='exam',
            field=models.ManyToManyField(to='exam.exam'),
        ),
    ]
