# Generated by Django 4.2 on 2023-05-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_answer_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='select',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
