# Generated by Django 4.2 on 2023-05-01 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0031_answer_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='student',
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
