# Generated by Django 4.2 on 2023-05-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0032_remove_answer_student_answer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='exam',
        ),
        migrations.AddField(
            model_name='answer',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
