# Generated by Django 4.2 on 2023-05-01 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0034_remove_answer_question_alter_answer_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='student_dones',
            field=models.ManyToManyField(related_name='exam_s_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
