# Generated by Django 4.2 on 2023-05-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0038_remove_answersheet_answers_answersheet_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='true',
            field=models.BooleanField(default=False),
        ),
    ]
