# Generated by Django 4.2 on 2023-04-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('d_1', models.CharField(max_length=100)),
                ('d_2', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
