# Generated by Django 4.2 on 2023-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='image',
            field=models.ImageField(null=True, upload_to='plans_image/'),
        ),
    ]
