# Generated by Django 4.2 on 2023-04-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plans_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='exam_num',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
