# Generated by Django 4.2 on 2023-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plans_exam_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='exam_num',
            field=models.IntegerField(null=True),
        ),
    ]
