# Generated by Django 4.2 on 2023-04-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_alter_plans_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
