# Generated by Django 4.2 on 2023-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_alter_plans_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exam_num',
            field=models.IntegerField(null=True),
        ),
    ]
