# Generated by Django 4.2 on 2023-04-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_alter_order_exam_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
