# Generated by Django 4.2 on 2023-04-27 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_coupon_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='exam_num',
        ),
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plans'),
        ),
    ]
