# Generated by Django 4.2 on 2023-04-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_remove_order_exam_num_order_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
