# Generated by Django 4.2 on 2023-04-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_order_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('plan', models.ManyToManyField(to='plans.plans')),
            ],
        ),
    ]
