# Generated by Django 4.2 on 2023-04-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0017_payhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='coupon',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
