# Generated by Django 4.2 on 2023-04-27 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0020_remove_payhistory_user_payhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='payhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
