# Generated by Django 4.2 on 2023-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='image',
            field=models.ImageField(default='default_images/avatar.png', upload_to='academy_images/'),
        ),
    ]
