# Generated by Django 4.2 on 2023-04-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_academy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='image',
            field=models.ImageField(default='default_images/academy.png', upload_to='academy_images/'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='image',
            field=models.ImageField(default='default_images/avatar.png', upload_to='owner_profile/'),
        ),
    ]
