# Generated by Django 4.2 on 2023-04-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_academy_image_alter_ownerprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='exam_num',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
