# Generated by Django 4.2 on 2023-04-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_academy_exam_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='now_academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.academy'),
        ),
    ]
