# Generated by Django 4.2 on 2023-04-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacherprofile_now_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='now_academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.academy'),
        ),
    ]
