# Generated by Django 4.2 on 2023-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile_now_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='now_courses',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='now_courses',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.courses'),
        ),
    ]
