# Generated by Django 4.2 on 2023-04-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_studentprofile_now_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='now_courses',
            field=models.ManyToManyField(to='accounts.courses'),
        ),
    ]
