# Generated by Django 4.2 on 2023-04-22 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='academy_default/default.png', upload_to='academy_images/')),
                ('url', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(related_name='academy_courses', to='accounts.courses')),
                ('students', models.ManyToManyField(related_name='academy_students', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='academy_teachers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('g_image', models.ImageField(upload_to='academy_gallery/')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_academy', to='academy.academy')),
            ],
        ),
    ]
