# Generated by Django 4.2 on 2023-04-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academygallery',
            name='academy',
        ),
        migrations.DeleteModel(
            name='Academy',
        ),
        migrations.DeleteModel(
            name='AcademyGallery',
        ),
    ]
